# Generated by Django 5.0.2 on 2024-03-12 18:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('codigo_alumno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('c_creditos', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
                ('numero_telefono', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Escuela_profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_creditos', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(200)])),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_egreso', models.DateField()),
                ('titulo', models.CharField(max_length=100)),
                ('codigo_alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App1.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='Escuela_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.escuela_profesional'),
        ),
        migrations.CreateModel(
            name='Trayectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleos', to='App1.egresado')),
            ],
        ),
    ]
